services:
  mysql:
    image: mysql:8.0
    container_name: fruitshoot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: fshoot
      MYSQL_DATABASE: fruitshoot
      MYSQL_USER: appuser
      MYSQL_PASSWORD: fshoot
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/docker-entrypoint-initdb.d 
    restart: unless-stopped

volumes:
  mysql_data:
